baseURL = "https://synelab.xyz/"
languageCode = "zh-cn"
title = "合成电子学实验室"

[pagination]
pagerSize = 10

enableRobotsTXT = true
enableEmoji = true
copyright = "© 2021–2026 合成电子学实验室 上海科技大学"

[params]
  labName = "合成电子学实验室"
  labSlogan = "以化成器 | Towards electronics, in a chemistry way"
  piName = "纪清清"
  piPhoto = "/images/pi.jpg"
  logo = "/images/logo.png"
  favicon = "/images/favicon.png"
  heroImage = "/images/hero.jpg"
  email = "jiqq@shanghaitech.edu.cn"
  phone = "(021)-20684747"
  address = "上海市浦东新区华夏中路393号物质学院6号楼503室"
  github = "https://github.com/synelab"
  shanghaitech = "https://www.shanghaitech.edu.cn/"
  spst = "https://spst.shanghaitech.edu.cn/"
  visitorCount = true

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[[menus.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menus.main]]
  name = "研究方向"
  url = "/research"
  weight = 2

[[menus.main]]
  name = "组员介绍"
  url = "/people"
  weight = 3

[[menus.main]]
  name = "成果及论文"
  url = "/publications"
  weight = 4

[[menus.main]]
  name = "课题组新闻"
  url = "/news"
  weight = 5

[[menus.main]]
  name = "加入我们"
  url = "/positions"
  weight = 6

[[menus.main]]
  name = "联系我们"
  url = "/contact"
  weight = 7

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
